server:
  port: 18084

#数据源的配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud_database?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 13822522655
    #这里报红，则把connector的依赖去掉scope
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    #在注册中心命名为user-provider
    name: user-provider

#配置eureka
eureka:
  client:
    service-url:
      #eureka注册中心（服务端）的地址
      defaultZone: http://localhost:18083/eureka
  instance:
    #设置本实例的ip地址
    ip-address: 127.0.0.1
    #启用ip地址进行注册
    prefer-ip-address: true
    lease-expiration-duration-in-seconds: 30 #租约续约间隔时间，默认30秒
    lease-renewal-interval-in-seconds: 90 #租约到期时效时间，默认90秒

