server:
  port: 18082
spring:
  application:
    #在注册中心命名为user-provider
    name: user-consumer

#配置eureka
eureka:
  client:
    service-url:
      #eureka注册中心（服务端）的地址
      defaultZone: http://localhost:18083/eureka
    #每隔30秒拉取一次
    registry-fetch-interval-seconds: 30

user-provider:
  ribbon:
# 修改服务地址轮询策略，默认是轮询，配置之后变随机
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
    ConnectTimeout: 10000 # 连接超时时间
    ReadTimeout: 2000 # 数据读取超时时间
    MaxAutoRetries: 1 # 最大重试次数(第一个服务)
    MaxAutoRetriesNextServer: 0 # 最大重试下一个服务次数(集群的情况才会用到)
    OkToRetryOnAllOperations: false # 无论是请求超时或者socket read timeout都进行重试

feign:
  hystrix: #开启熔断器
    enabled: true
  compression: #请求压缩
    request:
      enabled: true # 开启请求压缩
    response:
      enabled: true

# com.itheima 包下的日志级别都为Debug
logging:
  level:
    com.mochaoxiong: debug
