spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/springboot_database?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: 13822522655

redis:
  host: localhost
  port: 6379

#声明MyBatis映射配置文件
mybatis:
  mapper-locations: classpath:com/mochaoxiong/dao/*Mapper.xml


# 配置监控端点开启所有详情信息
management:
  endpoint:
    health:
      enabled: true
      show-details: always  #总是显示健康指标详细信息
  #设置开放所有web相关的端点信息
  endpoints:
    web:
      exposure:
        include: "*"  #开放所有监控【端点】
#
info:
  name: "mochaoxiong"
  age: 18
